FROM alpine:3.14

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN apk add --update npm && npm install && npm run build \
    && npm install -g serve && adduser -D appuser

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
