version: '3.8'

services:
    example-backend:
      image: example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=example-redis
    example-frontend:
      image: example-frontend
      ports:
        - 5000:5000
    example-redis:
      image: redis