version: '3.8'

services:
    example-backend:
      image: example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=example-redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DATABASE=postgres
      depends_on:
        - db
      container_name: example_backend
    example-frontend:
      image: example-frontend
      ports:
        - 5000:5000
      container_name: example_frontend
    example-redis:
      image: redis
      container_name: example_redis
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: password
      container_name: db
      volumes:
        - ./database:/var/lib/postgresql/data