FROM node:16

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN npm install && npm run build \
    npm install -g serve && useradd -m appuser

USER appuser

# And finally the command to run the application
CMD ["serve", "-s", "-l", "5000", "build"]
